// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdm_Vgm7UTy31k-_uZW0mI4Kwlro3-KdI',
    appId: '1:752760345570:web:6046eea6a2a70cfaed9fbb',
    messagingSenderId: '752760345570',
    projectId: 'flutter-final-exam-edafe',
    authDomain: 'flutter-final-exam-edafe.firebaseapp.com',
    storageBucket: 'flutter-final-exam-edafe.appspot.com',
    measurementId: 'G-4JWKX6ZL0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtlhb1o_AKiBShx-fBc5G9cxKq3cfpVK8',
    appId: '1:752760345570:android:e59b4a5de8ce884bed9fbb',
    messagingSenderId: '752760345570',
    projectId: 'flutter-final-exam-edafe',
    storageBucket: 'flutter-final-exam-edafe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS_VS0STd7csapRN6yk_--aa82teEHgpY',
    appId: '1:752760345570:ios:deb9bc633197574eed9fbb',
    messagingSenderId: '752760345570',
    projectId: 'flutter-final-exam-edafe',
    storageBucket: 'flutter-final-exam-edafe.appspot.com',
    iosBundleId: 'com.example.flutterFinalTest',
  );
}
